runtime: python27
api_version: 1
threadsafe: yes
service: adm

# env_variables:
#   API_KEY: <API key for projects app engine>

handlers:

  - url: /(.*\.(gif|png|ttf|woff|woff2|eot|svg|jpg|css|js|json)(|\.map))$
    static_files: dist/front-ng/\1
    upload: dist/front-ng/(.*)(|\.map)

  - url: /(.*)
    static_files: dist/front-ng/index.html
    upload: dist/front-ng/index.html

  - url: /
    static_files: dist/front-ng/index.html
    upload: dist/front-ng/index.html
  - url: /
    static_dir: dist/front-ng

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
